### ISSUE TITLE
'x' outside of string in unpack at C:/Perl64/site/lib/Win32/Wlan/API.pm

### ISSUE THREAD

**Issue by khalidelboray** [Corion/Win32-Wlan#1] opened 2019-01-26 19:20 UTC
Failes While Testing and using no test gives the same error while calling it

**Comment by Corion** [comment] 2022-12-03 09:15
This has been fixed and released as 0.07.

The cause was 64bit Windows API vs. 32bit Windows API.

**Closed by Corion** 2022-12-03 09:15 UTC
